### ISSUE TITLE
Make syntastic work with `xo`

### ISSUE THREAD

**Issue by arthurvr** [arthurvr/dotvim#12]
I now use it everywhere so let's make sure syntastic works fine with it. Just going to do a syntastic PR so this issue is a just a reminder to then [start linting JS again](https://github.com/arthurvr/dotvim/commit/8b557ef87de8752098e13f27e4cb58d9b1688bd1).

**Comment by sindresorhus** [comment]
XO issue: https://github.com/sindresorhus/xo/issues/28
